name: Integration Tests Default

on:
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  run-integration-tests:
    name: Run Integration Tests with Default
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix: 
#        dbEngine: ["mysql-aurora", "pg-aurora", "mysql-multi-az", "pg-multi-az"]
        dbEngine: ["pg-multi-az"]
    steps:
      - name: 'Clone repository'
        uses: actions/checkout@v4
      - name: "Set up JDK 8"
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 8
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.407'
      - name: Configure AWS Credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: dotnet_integration_test
          role-duration-seconds: 21600
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          output-credentials: true
      - name: Run Integration Tests
        run: |
          cd test/integration/host && ./gradlew --no-parallel --no-daemon test-all-${{ matrix.dbEngine }} --info
        env:
          RDS_DB_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ steps.creds.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.creds.outputs.aws-secret-access-key }}
          AWS_SESSION_TOKEN: ${{ steps.creds.outputs.aws-session-token }}
          MYSQL_VERSION: "default"
          PG_VERSION: "default"
      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-report-default-${{ matrix.dbEngine }}
          path: ./test/integration/reports
          retention-days: 5
