name: Publish to NuGet

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "Run ID of draft release workflow"
        required: true

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for dawidd6/action-download-artifact

jobs:
  publish-nuget:
    runs-on: windows-latest
    steps:
      - name: Download NuGet package artifact
        uses: dawidd6/action-download-artifact@v11
        with:
          name: nuget-packages
          run_id: ${{ github.event.inputs.run_id }}
          path: .\packages

      - name: Configure NuGet credential
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: ${{ secrets.NUGET_ACCESS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_NUGET_KEY_REGION }}

      - name: Publish to NuGet
        shell: pwsh
        run: |
          $nugetKey = aws secretsmanager get-secret-value --secret-id ${{ secrets.NUGET_SECRETS_ID }} --region ${{ secrets.AWS_NUGET_KEY_REGION }} --output text --query SecretString | ConvertFrom-Json
          dotnet nuget push .\packages\*.nupkg --source https://api.nuget.org/v3/index.json --api-key $nugetKey.Key

      - name: Get Github Action IP
        if: always()
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Remove Github Action IP
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress --group-name default --protocol all --port 0-65535 --cidr ${{ steps.ip.outputs.ipv4 }}/32
